service: my-express-application

package:
  exclude:
  - .circleci/**

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'