version: 2
jobs:
  build:
    steps:
      - checkout      
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - run:
          name: Deploy application 
          command: sls offline start 
